###
POST http://localhost:5000/register/user
X-Frontend-Key: 86d18ffe-09a5-43ef-8008-608dc117c4f476dae630-f1c6-4379-b8da-f1106f6c1f50
Content-Type: application/json

{
    "firstName" : "James",
    "lastName" : "John",
    "email" : "jamesjohn87@gmail.com",
    "password" : "1234",
    "dateOfBirth" : "07/14/2004",
    "phoneNumber": "08066859429",
    "bio": "Hi i'm victory a fullstack web developer focused on buliding high performance scalable web applications"
}
###
POST http://localhost:5000/signin/user
X-Frontend-Key: 86d18ffe-09a5-43ef-8008-608dc117c4f476dae630-f1c6-4379-b8da-f1106f6c1f50
Content-Type: application/json


{
    "email" : "nwanoruovictory87@gmail.com",
    "password" : "1234"
    
}

###
POST  http://localhost:5000/connection/user/add/1ed0d6e0-267d-4e53-a000-77a637de42d5
X-Frontend-Key: 86d18ffe-09a5-43ef-8008-608dc117c4f476dae630-f1c6-4379-b8da-f1106f6c1f50
Content-Type: application/json

{
    "userId" : "6a39d2617f20f881079fe878"
}

###
POST  http://localhost:5000/connection/contact/messages
X-Frontend-Key: 86d18ffe-09a5-43ef-8008-608dc117c4f476dae630-f1c6-4379-b8da-f1106f6c1f50
Content-Type: application/json

{
     "connectionId": "1ed0d6e0-267d-4e53-a000-77a637de42d5",
          "contactId": "8531f3d4-ff8c-49dd-a157-115c9f83cc11"
}

###
GET  http://localhost:5000/feeds/get/content